name: 'dbt_pipes'
version: '1.0.0'
config-version: 2

profile: 'dbt_pipes'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_pipes:
    0raw:
      materialized: view
    1cleaned:
      materialized: table
    2model:
      materialized: table
      +post-hook:
        sql: "-- EXPORT DATABASE 'export_edw' (FORMAT CSV, DELIMITER '|');"
vars:
  MODE: ''
