{#
    generated by dbt power user
#}
WITH source AS (
    SELECT * FROM {{ source('raw', 'iris_raw') }}
),

renamed AS (
    SELECT
        {{ adapter.quote("column0") }},
        {{ adapter.quote("column1") }},
        {{ adapter.quote("column2") }},
        {{ adapter.quote("column3") }},
        {{ adapter.quote("column4") }}
    FROM source
)

SELECT * FROM renamed
