name: dbt template CI on github

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: make install0
    - name: get some raw data
      run: make loaddb0
    - name: dbt deps
      run: dbt deps
    - name: check format
      run: make format
    - name: update models
      run: dbt build  
