name: dbt template CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: make install
    - name: load raw data
      run: make loaddb0
    - name: build models
      run: make run
    - name: test models
      run: make test
    - name: check format
      run: make format