name: Makefile CI

on: [push, pull_request]

jobs:
  build:
 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: make install
    - name: run
      run: make run
    - name: test
      run: make test
    - name: format
      run: make format
    
