name: dbt template CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: make install
    - name: load raw data
      run: make loaddb0
    - name: |
        dbt deps \
        dbt build 
      run: dbt build
    - name: check format
      run: make format
